// skillcarddata.js
// 각 스킬 카드의 정보와 중복 획득 가능 여부를 정의합니다.
// multi: true 속성이 없으면 기본적으로 1회만 획득 가능한 카드로 간주합니다.

export const skillCardList = {
    // --- Anomaly ---
    "anomaly-legend1": { type: "active", attrs: ["enthusiasm"], rarity: "Legend" },
    "anomaly-legend2": { type: "mental", attrs: ["preservation"], rarity: "Legend" },
    "anomaly-legend3": { type: "mental", attrs: [], rarity: "Legend" },
    "anomaly-legend4": { type: "active", attrs: [], rarity: "Legend" },
    "anomaly-legend5": { type: "mental", attrs: ["preservation"], rarity: "Legend" },
    "anomaly-r1": { type: "active", attrs: ["fullpower"], rarity: "R", multi: true },
    "anomaly-r2": { type: "active", attrs: ["enthusiasm"], rarity: "R", multi: true },
    "anomaly-r3": { type: "active", attrs: [], rarity: "R", multi: true },
    "anomaly-r3alt": { type: "active", attrs: ["enthusiasm"], rarity: "R", multi: true },
    "anomaly-r4": { type: "active", attrs: ["fullpower"], rarity: "R", multi: true },
    "anomaly-r4alt": { type: "active", attrs: ["fullpower"], rarity: "R", multi: true },
    "anomaly-r5": { type: "active", attrs: ["fullpower"], rarity: "R", multi: true },
    "anomaly-r6": { type: "active", attrs: ["enthusiasm"], rarity: "R", multi: true },
    "anomaly-r7": { type: "mental", attrs: ["preservation", "genki"], rarity: "R", multi: true },
    "anomaly-r8": { type: "mental", attrs: ["preservation", "fullpower", "genki"], rarity: "R", multi: true },
    "anomaly-r9": { type: "mental", attrs: ["preservation", "fullpower", "genki"], rarity: "R", multi: true },
    "anomaly-r10": { type: "mental", attrs: ["fullpower"], rarity: "R" },
    "anomaly-r11": { type: "mental", attrs: ["preservation"], rarity: "R", multi: true },
    "anomaly-r12": { type: "active", attrs: ["enthusiasm", "fullpower"], rarity: "R", multi: true },
    "anomaly-sr1": { type: "active", attrs: ["enthusiasm"], rarity: "SR", multi: true },
    "anomaly-sr1alt": { type: "mental", attrs: ["preservation"], rarity: "SR" },
    "anomaly-sr2": { type: "active", attrs: ["fullpower"], rarity: "SR", multi: true },
    "anomaly-sr3": { type: "active", attrs: [], rarity: "SR", multi: true },
    "anomaly-sr3alt": { type: "active", attrs: ["enthusiasm", "fullpower", "preservation"], rarity: "SR" },
    "anomaly-sr4": { type: "active", attrs: [], rarity: "SR", multi: true },
    "anomaly-sr4alt": { type: "mental", attrs: ["fullpower"], rarity: "SR" },
    "anomaly-sr5": { type: "mental", attrs: ["fullpower"], rarity: "SR" },
    "anomaly-sr6": { type: "active", attrs: ["enthusiasm"], rarity: "SR" },
    "anomaly-sr7": { type: "mental", attrs: [], rarity: "SR" },
    "anomaly-sr8": { type: "mental", attrs: [], rarity: "SR" },
    "anomaly-sr9": { type: "active", attrs: ["enthusiasm", "fullpower"], rarity: "SR", multi: true },
    "anomaly-sr10": { type: "active", attrs: ["enthusiasm"], rarity: "SR" },
    "anomaly-sr11": { type: "active", attrs: ["fullpower"], rarity: "SR" },
    "anomaly-sr12": { type: "active", attrs: [], rarity: "SR", multi: true },
    "anomaly-sr13": { type: "active", attrs: ["fullpower", "preservation"], rarity: "SR", multi: true },
    "anomaly-sr14": { type: "mental", attrs: ["fullpower", "genki"], rarity: "SR", multi: true },
    "anomaly-sr15": { type: "mental", attrs: ["preservation", "genki"], rarity: "SR", multi: true },
    "anomaly-sr16": { type: "mental", attrs: ["preservation", "genki", "fullpower"], rarity: "SR", multi: true },
    "anomaly-sr17": { type: "mental", attrs: ["preservation", "genki", "fullpower"], rarity: "SR", multi: true },
    "anomaly-sr18": { type: "mental", attrs: ["fullpower"], rarity: "SR" },
    "anomaly-sr19": { type: "mental", attrs: ["preservation"], rarity: "SR" },
    "anomaly-sr20": { type: "mental", attrs: ["preservation"], rarity: "SR" },
    "anomaly-sr21": { type: "active", attrs: ["enthusiasm"], rarity: "SR", multi: true },
    "anomaly-ssr1": { type: "active", attrs: ["fullpower"], rarity: "SSR" },
    "anomaly-ssr1alt": { type: "active", attrs: ["fullpower"], rarity: "SSR" },
    "anomaly-ssr2": { type: "active", attrs: ["enthusiasm"], rarity: "SSR" },
    "anomaly-ssr2alt": { type: "active", attrs: ["fullpower"], rarity: "SSR" },
    "anomaly-ssr3": { type: "active", attrs: ["enthusiasm", "fullpower"], rarity: "SSR" },
    "anomaly-ssr4": { type: "mental", attrs: ["preservation"], rarity: "SSR" },
    "anomaly-ssr5": { type: "active", attrs: ["preservation", "fullpower"], rarity: "SSR" },
    "anomaly-ssr6": { type: "active", attrs: ["preservation", "enthusiasm"], rarity: "SSR" },
    "anomaly-ssr7": { type: "active", attrs: ["enthusiasm"], rarity: "SSR" },
    "anomaly-ssr8": { type: "mental", attrs: ["preservation"], rarity: "SSR" },
    "anomaly-ssr9": { type: "mental", attrs: [], rarity: "SSR" },
    "anomaly-ssr10": { type: "mental", attrs: ["fullpower", "genki"], rarity: "SSR" },
    "anomaly-ssr11": { type: "mental", attrs: ["fullpower"], rarity: "SSR" },

    "anomaly-ssrchina_howlinglimited": { type: "mental", attrs: ["preservation"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrhiro_3rd": { type: "mental", attrs: ["genki", "preservation"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrhiro_miraclelimited": { type: "active", attrs: ["genki", "fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrhiro_valentinedist": { type: "mental", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrkotone_ameagariunit": { type: "mental", attrs: ["preservation"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrlilja_2nd": { type: "active", attrs: ["enthusiasm"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrlilja_3rd": { type: "active", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrlilja_sakuradist": { type: "active", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrmao_campusfes": { type: "mental", attrs: ["preservation"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrmao_yukidokenilimited": { type: "active", attrs: ["enthusiasm", "fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrmisuzu_1st": { type: "mental", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrrinami_campusfes": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrrinami_valentinelimited": { type: "mental", attrs: ["preservation"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsaki_gamusyaradist": { type: "active", attrs: ["enthusiasm", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsaki_sakuralimited": { type: "mental", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsena_1st": { type: "active", attrs: ["enthusiasm"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsena_endlesslimited": { type: "active", attrs: ["enthusiasm", "fullpower", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsena_starmineunit": { type: "mental", attrs: ["preservation", "fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsumika_2nd": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrsumika_dokimekiunit": { type: "active", attrs: ["enthusiasm", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrtemari_3rd": { type: "mental", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrtemari_yukidokenidist": { type: "active", attrs: ["enthusiasm"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrume_2nd": { type: "active", attrs: ["enthusiasm"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrume_campusfes": { type: "mental", attrs: ["fullpower"], rarity: "SSR", isKyoukaOnly: true },
    "anomaly-ssrmisuzu_3rd": { type: "active", attrs: ["enthusiasm"], rarity: "SSR", isKyoukaOnly: true },

    // --- Free ---
    "free-r1": { type: "mental", attrs: ["genki"], rarity: "R", multi: true },
    "free-r2": { type: "mental", attrs: ["genki"], rarity: "R" },
    "free-sr1": { type: "active", attrs: ["genki"], rarity: "SR", multi: true },
    "free-sr2": { type: "mental", attrs: [], rarity: "SR" },
    "free-sr3": { type: "mental", attrs: ["genki"], rarity: "SR", multi: true },
    "free-ssr1": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "free-ssr2": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "free-ssr3": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "free-ssr4": { type: "mental", attrs: [], rarity: "SSR" },

    // --- Logic ---
    "logic-legend1": { type: "mental", attrs: [], rarity: "Legend" },
    "logic-legend2": { type: "mental", attrs: ["goodimpression"], rarity: "Legend" },
    "logic-legend3": { type: "mental", attrs: ["motivation", "genki"], rarity: "Legend" },
    "logic-legend4": { type: "active", attrs: ["goodimpression"], rarity: "Legend" },
    "logic-legend5": { type: "acitve", attrs: ["genki"], rarity: "Legend" },
    "logic-r1": { type: "active", attrs: ["goodimpression"], rarity: "R", multi: true },
    "logic-r1alt": { type: "active", attrs: ["goodimpression"], rarity: "R", multi: true },
    "logic-r2": { type: "active", attrs: ["motivation"], rarity: "R", multi: true },
    "logic-r3": { type: "active", attrs: ["motivation"], rarity: "R", multi: true },
    "logic-r3alt": { type: "active", attrs: ["motivation", "genki"], rarity: "R", multi: true },
    "logic-r4": { type: "active", attrs: [], rarity: "R", multi: true },
    "logic-r5": { type: "active", attrs: [""], rarity: "R", multi: true },
    "logic-r6": { type: "mental", attrs: ["goodimpression", "genki"], rarity: "R", multi: true },
    "logic-r7": { type: "mental", attrs: ["motivation", "genki"], rarity: "R", multi: true },
    "logic-r8": { type: "mental", attrs: ["genki"], rarity: "R", multi: true },
    "logic-r9": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "R", multi: true },
    "logic-r10": { type: "mental", attrs: ["goodimpression", "genki"], rarity: "R", multi: true },
    "logic-r11": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "R", multi: true },
    "logic-r12": { type: "mental", attrs: ["goodimpression"], rarity: "R", multi: true },
    "logic-r13": { type: "active", attrs: ["genki"], rarity: "R" },
    "logic-r14": { type: "mental", attrs: ["goodimpression"], rarity: "R", multi: true },
    "logic-sr1": { type: "active", attrs: ["goodimpression"], rarity: "SR", multi: true },
    "logic-sr2": { type: "active", attrs: ["genki"], rarity: "SR", multi: true },
    "logic-sr3": { type: "active", attrs: [], rarity: "SR", multi: true },
    "logic-sr3alt": { type: "mental", attrs: ["motivation", "genki"], rarity: "SR" },
    "logic-sr4": { type: "active", attrs: ["genki"], rarity: "SR" },
    "logic-sr5": { type: "active", attrs: [], rarity: "SR" },
    "logic-sr6": { type: "mental", attrs: ["motivation", "genki"], rarity: "SR", multi: true },
    "logic-sr6alt": { type: "mental", attrs: ["goodimpression", "motivation", "genki"], rarity: "SR" },
    "logic-sr7": { type: "mental", attrs: ["goodimpression", "genki"], rarity: "SR", multi: true },
    "logic-sr8": { type: "mental", attrs: ["goodimpression"], rarity: "SR", multi: true },
    "logic-sr8alt": { type: "mental", attrs: ["goodimpression"], rarity: "SR" },
    "logic-sr9": { type: "mental", attrs: ["goodimpression"], rarity: "SR" },
    "logic-sr10": { type: "mental", attrs: ["motivation"], rarity: "SR" },
    "logic-sr11": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "SR", multi: true },
    "logic-sr12": { type: "mental", attrs: ["motivation", "genki"], rarity: "SR" },
    "logic-sr13": { type: "mental", attrs: ["motivation", "genki"], rarity: "SR", multi: true },
    "logic-sr14": { type: "mental", attrs: ["goodimpression", "genki"], rarity: "SR", multi: true },
    "logic-sr15": { type: "mental", attrs: ["motivation"], rarity: "SR" },
    "logic-sr16": { type: "mental", attrs: ["motivation", "goodimpression"], rarity: "SR" },
    "logic-sr17": { type: "mental", attrs: ["goodimpression"], rarity: "SR" },
    "logic-sr18": { type: "active", attrs: [], rarity: "SR" },
    "logic-ssr1": { type: "active", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr1alt": { type: "active", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr2": { type: "active", attrs: ["motivation"], rarity: "SSR" },
    "logic-ssr2alt": { type: "active", attrs: ["genki"], rarity: "SSR" },
    "logic-ssr3": { type: "mental", attrs: [], rarity: "SSR" },
    "logic-ssr4": { type: "mental", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr5": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "SSR" },
    "logic-ssr6": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "logic-ssr7": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "SSR" },
    "logic-ssr8": { type: "mental", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr9": { type: "active", attrs: [], rarity: "SSR" },
    "logic-ssr10": { type: "active", attrs: [], rarity: "SSR" },
    "logic-ssr11": { type: "active", attrs: ["genki"], rarity: "SSR" },
    "logic-ssr12": { type: "active", attrs: [], rarity: "SSR" },
    "logic-ssr13": { type: "mental", attrs: ["genki", "goodimpression", "motivation"], rarity: "SSR" },

    "logic-ssrchina_1st": { type: "active", attrs: ["genki", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrchina_campusfes": { type: "active", attrs: ["genki", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrchina_yukidokenilimited": { type: "active", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrhiro_1st": { type: "mental", attrs: ["genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrhiro_campusfes": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrhiro_michinaruunit": { type: "active", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrkotone_1st": { type: "mental", attrs: ["goodimpression", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrkotone_campusfes": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrkotone_christmasdist": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrkotone_kanmurilimited": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrlilja_1st": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrlilja_christmaslimited": { type: "active", attrs: ["genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrlilja_howlinglimited": { type: "mental", attrs: ["genki", "goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrmao_2nd": { type: "active", attrs: ["motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrmao_miraclelimited": { type: "mental", attrs: ["motivation", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrmisuzu_2nd": { type: "active", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrmisuzu_campusfes": { type: "active", attrs: ["motivation", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrmisuzu_endlessdist": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrrinami_2nd": { type: "mental", attrs: ["genki", "goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrrinami_3rd": { type: "mental", attrs: ["genki", "goodimpression", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrrinami_onsen": { type: "active", attrs: ["genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsaki_2nd": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsaki_3rd": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsaki_ameagariunit": { type: "mental", attrs: ["motivation", "genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsaki_kanmuridist": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsena_2nd": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsena_3rd": { type: "mental", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsena_valentinelimited": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsumika_campusfes": { type: "mental", attrs: ["genki", "goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsumika_miracledist": { type: "mental", attrs: ["genki", "motivation", "goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrsumika_summerlimited": { type: "mental", attrs: ["motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrtemari_2nd": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrtemari_gamusyaralimited": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrtemari_halloweenlimited": { type: "mental", attrs: ["goodimpression", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrtsubame_1st": { type: "mental", attrs: ["goodimpression"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrume_1st": { type: "mental", attrs: ["genki"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrume_3rd": { type: "mental", attrs: ["genki", "motivation"], rarity: "SSR", isKyoukaOnly: true },
    "logic-ssrume_starmineunit": { type: "mental", attrs: ["genki", "goodimpression"], rarity: "SSR", isKyoukaOnly: true },

    // --- Sense ---
    "sense-legend1": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "Legend" },
    "sense-legend2": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "Legend" },
    "sense-legend3": { type: "active", attrs: ["goodcondition", "concentration"], rarity: "Legend" },
    "sense-legend4": { type: "active", attrs: [], rarity: "Legend" },
    "sense-legend5": { type: "active", attrs: [], rarity: "Legend" },
    "sense-r1": { type: "active", attrs: ["goodcondition"], rarity: "R", multi: true },
    "sense-r2": { type: "active", attrs: [], rarity: "R", multi: true },
    "sense-r2alt": { type: "active", attrs: ["goodcondition"], rarity: "R", multi: true },
    "sense-r3": { type: "active", attrs: ["concentration"], rarity: "R", multi: true },
    "sense-r4": { type: "active", attrs: [], rarity: "R", multi: true },
    "sense-r5": { type: "active", attrs: ["concentration"], rarity: "R", multi: true },
    "sense-r6": { type: "active", attrs: [""], rarity: "R", multi: true },
    "sense-r7": { type: "active", attrs: [], rarity: "R", multi: true },
    "sense-r8": { type: "mental", attrs: ["concentration"], rarity: "R", multi: true },
    "sense-r8alt": { type: "active", attrs: ["concentration"], rarity: "R", multi: true },
    "sense-r9": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "R", multi: true },
    "sense-r10": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "R", multi: true },
    "sense-r11": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "R" },
    "sense-r12": { type: "active", attrs: [], rarity: "R", multi: true },
    "sense-r13": { type: "active", attrs: ["goodcondition", "concentration"], rarity: "R" },
    "sense-sr1": { type: "active", attrs: [], rarity: "SR", multi: true },
    "sense-sr1alt": { type: "mental", attrs: ["goodcondition"], rarity: "SR" },
    "sense-sr2": { type: "active", attrs: ["goodcondition"], rarity: "SR", multi: true },
    "sense-sr3": { type: "active", attrs: ["concentraiton"], rarity: "SR", multi: true },
    "sense-sr4": { type: "active", attrs: [], rarity: "SR", multi: true },
    "sense-sr5": { type: "active", attrs: ["goodcondition"], rarity: "SR", multi: true },
    "sense-sr6": { type: "active", attrs: ["genki"], rarity: "SR" },
    "sense-sr6alt": { type: "mental", attrs: ["concentraiton"], rarity: "SR" },
    "sense-sr7": { type: "active", attrs: ["concentraiton", "genki"], rarity: "SR" },
    "sense-sr8": { type: "active", attrs: ["goodcondition"], rarity: "SR" },
    "sense-sr9": { type: "mental", attrs: ["concentration", "genki"], rarity: "SR", multi: true },
    "sense-sr9alt": { type: "mental", attrs: ["concentration"], rarity: "SR" },
    "sense-sr10": { type: "mental", attrs: ["goodcondition", "genki"], rarity: "SR", multi: true },
    "sense-sr11": { type: "mental", attrs: [], rarity: "SR" },
    "sense-sr12": { type: "mental", attrs: ["concentration"], rarity: "SR" },
    "sense-sr13": { type: "mental", attrs: ["concentration", "goodcondition"], rarity: "SR", multi: true },
    "sense-sr14": { type: "mental", attrs: ["goodcondition"], rarity: "SR", multi: true },
    "sense-sr15": { type: "mental", attrs: ["concentration", "genki"], rarity: "SR", multi: true },
    "sense-sr16": { type: "mental", attrs: ["concentration"], rarity: "SR" },
    "sense-sr17": { type: "mental", attrs: ["concentration", "genki"], rarity: "SR", multi: true },
    "sense-sr18": { type: "mental", attrs: ["goodcondition", "genki"], rarity: "SR", multi: true },
    "sense-sr19": { type: "active", attrs: ["genki"], rarity: "SR", multi: true },
    "sense-sr20": { type: "active", attrs: ["concentration"], rarity: "SR" },
    "sense-sr21": { type: "mental", attrs: ["concentration", "genki"], rarity: "SR", multi: true },
    "sense-ssr1": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr1alt": { type: "active", attrs: ["concentration"], rarity: "SSR" },
    "sense-ssr2": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr2alt": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr3": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "sense-ssr4": { type: "mental", attrs: [], rarity: "SSR" },
    "sense-ssr5": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "SSR" },
    "sense-ssr6": { type: "mental", attrs: ["concentration"], rarity: "SSR" },
    "sense-ssr7": { type: "active", attrs: ["goodcondition"], rarity: "SSR" },
    "sense-ssr8": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr9": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr10": { type: "active", attrs: ["concentration"], rarity: "SSR" },
    "sense-ssr11": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "SSR" },

    "sense-ssrchina_2nd": { type: "mental", attrs: ["genki"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrchina_3rd": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrchina_halloweendist": { type: "active", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrchina_michinaruunit": { type: "active", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrchina_onsen": { type: "mental", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrhiro_2nd": { type: "active", attrs: ["genki"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrhiro_halloweenlimited": { type: "mental", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrkotone_2nd": { type: "mental", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrkotone_3rd": { type: "mental", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrkotone_gamusyaralimited": { type: "active", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrlilja_campusfes": { type: "active", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrlilja_dokimekiunit": { type: "active", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrlilja_kanmurilimited": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrmao_1st": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrmao_3rd": { type: "mental", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrmao_summerdist": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrmisuzu_starmineunit": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrrinami_1st": { type: "mental", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrrinami_howlingdist": { type: "mental", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrrinami_summerlimited": { type: "active", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsaki_1st": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsaki_animate": { type: "active", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsaki_campusfes": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsena_campusfes": { type: "active", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsumika_1st": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsumika_3rd": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrsumika_sakuralimited": { type: "mental", attrs: ["goodcondition", "concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrtemari_1st": { type: "active", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrtemari_ameagariunit": { type: "mental", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrtemari_campusfes": { type: "active", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrtsubame_campusfes": { type: "active", attrs: [], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrume_christmaslimited": { type: "mental", attrs: ["goodcondition"], rarity: "SSR", isKyoukaOnly: true },
    "sense-ssrume_endlesslimited": { type: "active", attrs: ["concentration"], rarity: "SSR", isKyoukaOnly: true },

    "sense-prima_mao1": { type: "mental", attrs: [], rarity: "legend", primastella: true },
    "anomaly-prima_misuzu1": { type: "active", attrs: [], rarity: "legend", primastella: true },
    "logic-prima_rinami1": { type: "mental", attrs: [], rarity: "legend", primastella: true },
    "anomaly-prima_temari1": { type: "active", attrs: [], rarity: "legend", primastella: true },
};
