// skillcarddata.js
// 각 스킬 카드의 정보와 중복 획득 가능 여부를 정의합니다.
// multi: true 속성이 없으면 기본적으로 1회만 획득 가능한 카드로 간주합니다.

export const skillCardList = {
    // --- Anomaly ---
    "anomaly-legend1": { type: "active", attrs: ["enthusiasm"], rarity: "Legend" },
    "anomaly-legend2": { type: "mental", attrs: [], rarity: "Legend" },
    "anomaly-legend3": { type: "mental", attrs: [], rarity: "Legend" },
    "anomaly-r1": { type: "active", attrs: ["fullpower"], rarity: "R", multi:true },
    "anomaly-r2": { type: "active", attrs: ["enthusiasm"], rarity: "R" , multi:true},
    "anomaly-r3": { type: "active", attrs: [], rarity: "R" , multi:true},
    "anomaly-r3alt": { type: "active", attrs: ["enthusiasm"], rarity: "R" , multi:true},
    "anomaly-r4": { type: "active", attrs: ["fullpower"], rarity: "R", multi:true },
    "anomaly-r4alt": { type: "active", attrs: ["fullpower"], rarity: "R" , multi:true},
    "anomaly-r5": { type: "active", attrs: ["fullpower"], rarity: "R" , multi:true },
    "anomaly-r6": { type: "active", attrs: ["enthusiasm"], rarity: "R" , multi:true },
    "anomaly-r7": { type: "mental", attrs: ["preservation","genki"], rarity: "R" , multi:true },
    "anomaly-r8": { type: "mental", attrs: ["preservation","fullpower","genki"], rarity: "R" , multi:true },
    "anomaly-r9": { type: "mental", attrs: ["preservation","fullpower","genki"], rarity: "R" , multi:true },
    "anomaly-r10": {  type: "mental", attrs: ["fullpower"], rarity: "R" },
    "anomaly-r11": { type: "mental", attrs: ["preservation"], rarity: "R" , multi:true },
    "anomaly-r12": { type: "active", attrs: ["enthusiasm","fullpower"], rarity: "R" , multi:true},
    "anomaly-sr1": { type: "active", attrs: ["enthusiasm"], rarity: "SR", multi:true},
    "anomaly-sr1alt": { type: "mental", attrs: ["preservation"], rarity: "SR" },
    "anomaly-sr2": { type: "active", attrs: ["fullpower"], rarity: "SR", multi:true},
    "anomaly-sr3": { type: "active", attrs: [], rarity: "SR", multi:true},
    "anomaly-sr3alt": {type: "active", attrs: ["enthusiasm","fullpower"], rarity: "SR"},
    "anomaly-sr4": { type: "active", attrs: [], rarity: "SR", multi:true },
    "anomaly-sr4alt": { type: "mental", attrs: ["fullpower"], rarity: "SR"},
    "anomaly-sr5": { type: "mental", attrs: ["fullpower"], rarity: "SR"},
    "anomaly-sr6": { type: "active", attrs: ["enthusiasm"], rarity: "SR"},
    "anomaly-sr7": { type: "mental", attrs: [], rarity: "SR"},
    "anomaly-sr8": { type: "mental", attrs: [], rarity: "SR"},
    "anomaly-sr9": { type: "active", attrs: ["enthusiasm","fullpower"], rarity: "SR", multi:true},
    "anomaly-sr10": {type: "active", attrs: ["enthusiasm"], rarity: "SR"},
    "anomaly-sr11": { type: "active", attrs: ["fullpower"], rarity: "SR"},
    "anomaly-sr12": { type: "active", attrs: [], rarity: "SR" , multi:true},
    "anomaly-sr13": { type: "active", attrs: ["fullpower"], rarity: "SR", multi:true},
    "anomaly-sr14": {  type: "mental", attrs: ["fullpower","genki"], rarity: "SR", multi:true},
    "anomaly-sr15": { type: "mental", attrs: ["preservation","genki"], rarity: "SR", multi:true},
    "anomaly-sr16": { type: "mental", attrs: ["preservation","genki","fullpower"], rarity: "SR", multi:true},
    "anomaly-sr17": { type: "mental", attrs: ["preservation","genki","fullpower"], rarity: "SR", multi:true},
    "anomaly-sr18": { type: "mental", attrs: ["fullpower"], rarity: "SR"},
    "anomaly-sr19": { type: "mental", attrs: ["preservation"], rarity: "SR"},
    "anomaly-sr20": { type: "mental", attrs: ["preservation"], rarity: "SR"},
    "anomaly-sr21": { type: "active", attrs: ["enthusiasm"], rarity: "SR", multi:true},
    "anomaly-ssr1": { type: "active", attrs: ["fullpower"], rarity: "SSR" },
    "anomaly-ssr2": { type: "active", attrs: ["enthusiasm"], rarity: "SSR" },
    "anomaly-ssr3": { type: "active", attrs: ["enthusiasm","fullpower"], rarity: "SSR" },
    "anomaly-ssr4": { type: "mental", attrs: ["preservation"], rarity: "SSR" },
    "anomaly-ssr5": { type: "active", attrs: ["preservation","fullpower"], rarity: "SSR" },
    "anomaly-ssr6": { type: "active", attrs: ["preservation","enthusiasm"], rarity: "SSR" },
    "anomaly-ssr7": { type: "active", attrs: ["enthusiasm"], rarity: "SSR" },
    "anomaly-ssr8": { type: "mental", attrs: ["preservation"], rarity: "SSR" },
    "anomaly-ssr9": { type: "mental", attrs: [], rarity: "SSR" },
    "anomaly-ssr10": { type: "mental", attrs: ["fullpower","genki"], rarity: "SSR" },
    "anomaly-ssr11": { type: "mental", attrs: ["fullpower"], rarity: "SSR" },

    // --- Free ---
    "free-r1": { type: "mental", attrs: ["genki"], rarity: "R" , multi:true},
    "free-r2": { type: "mental", attrs: ["genki"], rarity: "R" },
    "free-sr1": { type: "active", attrs: ["genki"], rarity: "SR" , multi:true},
    "free-sr2": { type: "mental", attrs: [], rarity: "SR" },
    "free-sr3": { type: "mental", attrs: ["genki"], rarity: "SR" , multi:true},
    "free-ssr1": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "free-ssr2": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "free-ssr3": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "free-ssr4": { type: "mental", attrs: [], rarity: "SSR" },

    // --- Logic ---
    "logic-legend1": { type: "mental", attrs: [], rarity: "Legend" },
    "logic-legend2": { type: "mental", attrs: ["goodimpression"], rarity: "Legend" },
    "logic-legend3": { type: "mental", attrs: ["motivation","genki"], rarity: "Legend" },
    "logic-r1": { type: "active", attrs: ["goodimpression"], rarity: "R" ,multi:true},
    "logic-r1alt": { type: "active", attrs: ["goodimpression"], rarity: "R" ,multi:true},
    "logic-r2": { type: "active", attrs: ["motivation"], rarity: "R" ,multi:true },
    "logic-r3": { type: "active", attrs: ["motivation"], rarity: "R" ,multi:true},
    "logic-r3alt": { type: "active", attrs: ["motivation","genki"], rarity: "R" ,multi:true},
    "logic-r4": { type: "active", attrs: [], rarity: "R" ,multi:true},
    "logic-r5": { type: "active", attrs: [""], rarity: "R" ,multi:true},
    "logic-r6": { type: "mental", attrs: ["goodimpression","genki"], rarity: "R" ,multi:true},
    "logic-r7": { type: "mental", attrs: ["motivation","genki"], rarity: "R" ,multi:true },
    "logic-r8": { type: "mental", attrs: ["genki"], rarity: "R" ,multi:true},
    "logic-r9": { type: "mental", attrs: ["goodimpression","motivation"], rarity: "R" ,multi:true},
    "logic-r10": { type: "mental", attrs: ["goodimpression","genki"], rarity: "R" ,multi:true },
    "logic-r11": { type: "mental", attrs: ["goodimpression","motivation"], rarity: "R" ,multi:true },
    "logic-r12": { type: "mental", attrs: ["goodimpression"], rarity: "R" ,multi:true  },
    "logic-r13": { type: "active", attrs: ["genki"], rarity: "R"},
    "logic-r14": { type: "mental", attrs: ["goodimpression"], rarity: "R" ,multi:true },
    "logic-sr1": { type: "active", attrs: ["goodimpression"], rarity: "SR" ,multi:true },
    "logic-sr2": { type: "active", attrs: ["genki"], rarity: "SR" ,multi:true },
    "logic-sr3": { type: "active", attrs: [], rarity: "SR" ,multi:true },
    "logic-sr3alt": { type: "mental", attrs: ["motivation","genki"], rarity: "SR"},
    "logic-sr4": { type: "active", attrs: ["genki"], rarity: "SR"},
    "logic-sr5": { type: "active", attrs: [], rarity: "SR"},
    "logic-sr6": {  type: "mental", attrs: ["motivation","genki"], rarity: "SR", multi:true},
    "logic-sr6alt": { type: "mental", attrs: ["goodimpression","motivation","genki"], rarity: "SR" },    
    "logic-sr7": { type: "mental", attrs: ["goodimpression","genki"], rarity: "SR", multi:true },
    "logic-sr8": { type: "mental", attrs: ["goodimpression"], rarity: "SR", multi:true },
    "logic-sr8alt": { type: "mental", attrs: ["goodimpression"], rarity: "SR"},
    "logic-sr9": {type: "mental", attrs: ["goodimpression"], rarity: "SR"},
    "logic-sr10": {type: "mental", attrs: ["motivation"], rarity: "SR"},
    "logic-sr11": {type: "mental", attrs: ["goodimpression","motivation"], rarity: "SR", multi:true},
    "logic-sr12": {type: "mental", attrs: ["motivation","genki"], rarity: "SR"},
    "logic-sr13": {type: "mental", attrs: ["motivation","genki"], rarity: "SR",multi:true},
    "logic-sr14": { type: "mental", attrs: ["goodimpression","genki"], rarity: "SR",multi:true },
    "logic-sr15": { type: "mental", attrs: ["motivation"], rarity: "SR" },
    "logic-sr16": { type: "mental", attrs: ["motivation","goodimpression"], rarity: "SR"},
    "logic-sr17": { type: "mental", attrs: ["goodimpression"], rarity: "SR"},
    "logic-sr18": { type: "active", attrs: [], rarity: "SR" },
    "logic-ssr1": { type: "active", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr2": { type: "active", attrs: ["motivation"], rarity: "SSR" },
    "logic-ssr3": { type: "mental", attrs: [], rarity: "SSR" },
    "logic-ssr4": { type: "mental", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr5": { type: "mental", attrs: ["goodimpression","motivation"], rarity: "SSR" },
    "logic-ssr6": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "logic-ssr7": { type: "mental", attrs: ["goodimpression","motivation"], rarity: "SSR" },
    "logic-ssr8": { type: "mental", attrs: ["goodimpression"], rarity: "SSR" },
    "logic-ssr9": { type: "active", attrs: [], rarity: "SSR" },
    "logic-ssr10": { type: "active", attrs: [], rarity: "SSR" },
    "logic-ssr11": { type: "active", attrs: ["genki"], rarity: "SSR" },
    "logic-ssr12": { type: "active", attrs: [], rarity: "SSR" },
    "logic-ssr13": { type: "mental", attrs: ["genki","goodimpression","motivation"], rarity: "SSR" },

    // --- Sense ---
    "sense-legend1": { type: "mental", attrs: ["goodcondition","concentration"], rarity: "Legend" },
    "sense-legend2": { type: "mental", attrs: ["goodcondition","concentration"], rarity: "Legend" },
    "sense-legend3": { type: "active", attrs: ["goodcondition","concentration"], rarity: "Legend" },
    "sense-r1": { type: "active", attrs: ["goodcondition"], rarity: "R",multi:true },
    "sense-r2": { type: "active", attrs: [], rarity: "R",multi:true },
    "sense-r2alt": { type: "active", attrs: ["goodcondition"], rarity: "R",multi:true },
    "sense-r3": { type: "active", attrs: ["concentration"], rarity: "R",multi:true },
    "sense-r4": { type: "active", attrs: [], rarity: "R",multi:true},
    "sense-r5": { type: "active", attrs: ["concentration"], rarity: "R",multi:true },
    "sense-r6": { type: "active", attrs: [""], rarity: "R",multi:true },
    "sense-r7": { type: "active", attrs: [], rarity: "R",multi:true },
    "sense-r8": { type: "mental", attrs: ["concentration"], rarity: "R",multi:true },
    "sense-r8alt": { type: "active", attrs: ["concentration"], rarity: "R",multi:true},
    "sense-r9": {type: "mental", attrs: ["goodcondition","concentration"], rarity: "R",multi:true },
    "sense-r10": {type: "mental", attrs: ["goodcondition","concentration"], rarity: "R",multi:true  },
    "sense-r11": {type: "mental", attrs: ["goodcondition","concentration"], rarity: "R" },
    "sense-r12": { type: "active", attrs: [], rarity: "R",multi:true},
    "sense-r13": {type: "active", attrs: ["goodcondition","concentration"], rarity: "R" },
    "sense-sr1": { type: "active", attrs: [], rarity: "SR",multi:true},
    "sense-sr1alt": { type: "mental", attrs: ["goodcondition"], rarity: "SR" },
    "sense-sr2": { type: "active", attrs: ["goodcondition"], rarity: "SR",multi:true },
    "sense-sr3": { type: "active", attrs: ["concentraiton"], rarity: "SR",multi:true},
    "sense-sr4": { type: "active", attrs: [], rarity: "SR",multi:true},
    "sense-sr5": { type: "active", attrs: ["goodcondition"], rarity: "SR",multi:true},
    "sense-sr6": { type: "active", attrs: ["genki"], rarity: "SR"},
    "sense-sr6alt": { type: "mental", attrs: ["concentraiton"], rarity: "SR"},
    "sense-sr7": { type: "active", attrs: ["concentraiton","genki"], rarity: "SR"},
    "sense-sr8": {type: "active", attrs: ["goodcondition"], rarity: "SR"},
    "sense-sr9": {type: "mental", attrs: ["concentration","genki"], rarity: "SR",multi:true},
    "sense-sr9alt": {type: "mental", attrs: ["concentration"], rarity: "SR"},
    "sense-sr10": {type: "mental", attrs: ["goodcondition","genki"], rarity: "SR",multi:true},
    "sense-sr11": {type: "mental", attrs: [], rarity: "SR"},
    "sense-sr12": {type: "mental", attrs: ["concentration"], rarity: "SR"},
    "sense-sr13": {type: "mental", attrs: ["concentration","goodcondition"], rarity: "SR",multi:true},
    "sense-sr14": {type: "mental", attrs: ["goodcondition"], rarity: "SR",multi:true},
    "sense-sr15": {type: "mental", attrs: ["concentration","genki"], rarity: "SR",multi:true},
    "sense-sr16": {type: "mental", attrs: ["concentration"], rarity: "SR"},
    "sense-sr17": {type: "mental", attrs: ["concentration","genki"], rarity: "SR",multi:true},
    "sense-sr18": {type: "mental", attrs: ["goodcondition","genki"], rarity: "SR",multi:true},
    "sense-sr19": {type: "active", attrs: ["genki"], rarity: "SR",multi:true},
    "sense-sr20": {type: "active", attrs: ["goodcondition","concentration"], rarity: "SR"},
    "sense-sr21": {type: "mental", attrs: ["concentration","genki"], rarity: "SR",multi:true},
    "sense-ssr1": {type: "active", attrs: [], rarity: "SSR"},
    "sense-ssr2": {type: "active", attrs: [], rarity: "SSR"},
    "sense-ssr3": { type: "mental", attrs: ["genki"], rarity: "SSR" },
    "sense-ssr4": { type: "mental", attrs: [], rarity: "SSR" },
    "sense-ssr5": { type: "mental", attrs: ["goodcondition","concentration"], rarity: "SSR" },
    "sense-ssr6": { type: "mental", attrs: ["concentration"], rarity: "SSR" },
    "sense-ssr7": { type: "active", attrs: ["goodcondition"], rarity: "SSR" },
    "sense-ssr8": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr9": { type: "active", attrs: [], rarity: "SSR" },
    "sense-ssr10": { type: "active", attrs: ["concentration"], rarity: "SSR" },
    "sense-ssr11": { type: "mental", attrs: ["goodcondition","concentration"], rarity: "SSR" }
};
